---
- name: Create user
  hosts: all
  become: true
  tasks:
    - name: Create new user
      user:
        name: ubuntu
    - name: Create .ssh folder
      file:
        path: /home/ubuntu/.ssh/
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0700
    - name: Upload SSH key
      copy:
        src: /home/roman/.ssh/yacloud.pub
        dest: /home/ubuntu/.ssh/authorized_keys
        owner: ubuntu
        group: ubuntu
        mode: 0600
